name: TheMarkersParser
version: 0.1.0.2
license: MIT
author: Miguel Aguiar
maintainer: 102391413+mirvoxtm@users.noreply.github.com
category: Text
extra-source-files:
  - CHANGELOG.md

dependencies:
  - base
  - directory
  - filepath
  - Markers

library:
  source-dirs: src
  exposed-modules: []
  ghc-options: -Wall
  default-language: GHC2021

executables:
  TheMarkersParser:
    main: Main.hs
    source-dirs: src
    ghc-options: -Wall
    dependencies:
      - base
      - directory
      - filepath
      - Markers
    default-language: GHC2021